//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalSahabat
{
    using System;
    using System.Collections.Generic;
    
    public partial class StuffType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StuffType()
        {
            this.RentRecords = new HashSet<RentRecord>();
        }
    
        public int id { get; set; }
        public string NamaBarang { get; set; }
        public string InfoBarang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentRecord> RentRecords { get; set; }
    }
}
